from datetime import datetime, timezone
from database.db import one, execute


def log_event(session_id, category, actor, score, details):
    """Log a security event to the database."""
    execute(
        "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
        (
            session_id,
            category,
            actor,
            "REJECT",
            score,
            details,
            datetime.now(timezone.utc).isoformat(),
        ),
    )


# ── Attack Knowledge Base ────────────────────────────────────────────
# Comprehensive educational content for each attack type, used both
# by the attack simulation and the /api/attack-info endpoint.

ATTACK_KNOWLEDGE_BASE = {
    "forgery": {
        "name": "Signature Forgery",
        "icon": "🔨",
        "severity": "CRITICAL",
        "severity_score": 94,
        "description": (
            "A forgery attack attempts to create or modify a digital signature "
            "without possessing the signer's private key. The attacker either "
            "fabricates a completely new signature or alters the signed message "
            "while trying to keep the signature valid."
        ),
        "how_it_works": [
            "The attacker intercepts a legitimately signed message in transit between Alice and Bob.",
            "They modify the message content (e.g., changing 'Transfer $100' to 'Transfer $10,000').",
            "The attacker attempts to reuse the original quantum signature with the tampered message.",
            "The system re-computes the SHA-256 hash of the message and detects the hash mismatch.",
            "The forged message is rejected because the quantum-signed hash binding is broken.",
        ],
        "real_world_example": (
            "In 2011, the DigiNotar CA was compromised, allowing attackers to forge SSL certificates "
            "for major websites including google.com. This enabled man-in-the-middle attacks on "
            "500,000+ Iranian users. Quantum-secured signature binding would have prevented certificate forgery."
        ),
        "countermeasures": [
            "SHA-256 cryptographic hash binding — any message change invalidates the signature",
            "Quantum Bell state entanglement ties the signature to the exact message content",
            "One-time session tokens prevent signature reuse across different messages",
            "Immutable audit trail logs all signature generation with timestamps",
        ],
        "quantum_defense": (
            "In this system, the signature is bound to the message through a SHA-256 hash "
            "that is generated alongside the quantum Bell state measurement. The hash integrity "
            "check (Step 5 in verification) recomputes the hash from the stored message and "
            "compares it to the original. Any modification breaks the quantum-classical binding, "
            "making forgery detectable with 100% accuracy."
        ),
    },
    "impersonation": {
        "name": "Identity Impersonation",
        "icon": "🎭",
        "severity": "HIGH",
        "severity_score": 92,
        "description": (
            "An impersonation attack occurs when a malicious actor pretends to be "
            "the legitimate signer. The attacker uses social engineering or stolen "
            "credentials to forge the identity associated with a quantum signature, "
            "attempting to gain unauthorized trust."
        ),
        "how_it_works": [
            "Mallory learns that Alice has a trusted signing relationship with Bob.",
            "Mallory creates or intercepts a signature session originally generated by Alice.",
            "Mallory presents the session to Bob, claiming to be Alice (the original signer).",
            "The system checks the signer identity stored during generation against the verification request.",
            "The identity mismatch is detected — Mallory's identity doesn't match Alice's quantum-bound identity.",
        ],
        "real_world_example": (
            "In the 2020 Twitter hack, attackers impersonated high-profile accounts (Elon Musk, Barack Obama) "
            "to post fraudulent cryptocurrency messages. A quantum identity binding system would ensure "
            "that each message is cryptographically tied to the true sender's identity."
        ),
        "countermeasures": [
            "Quantum identity binding — signer identity is recorded at signature generation time",
            "Bell state measurement creates a unique quantum fingerprint for each signer-session pair",
            "Role-based access control limits who can verify (authorized verifier list)",
            "Full audit trail with actor logging exposes impersonation attempts",
        ],
        "quantum_defense": (
            "The quantum teleportation protocol binds the signer's identity to the Bell state measurement "
            "at generation time. During verification, the system checks whether the presenting actor matches "
            "the original signer. In a true quantum implementation, the entangled pair would be unique to "
            "Alice's quantum key, making impersonation physically impossible without her quantum device."
        ),
    },
    "replay": {
        "name": "Replay Attack",
        "icon": "🔄",
        "severity": "CRITICAL",
        "severity_score": 97,
        "description": (
            "A replay attack captures a valid, authenticated transaction and retransmits "
            "it to trick the system into accepting it again. Even though the original "
            "signature is genuine, using it a second time violates the one-time-use "
            "security protocol."
        ),
        "how_it_works": [
            "Mallory eavesdrops on the communication channel between Alice and Bob.",
            "Mallory captures a legitimate, verified signature session (session ID + credentials).",
            "After the original transaction completes, Mallory replays the same session to the server.",
            "The system checks the 'consumed' flag in the database — the session was already used.",
            "The replayed session is rejected because the one-time quantum token has been invalidated.",
        ],
        "real_world_example": (
            "Replay attacks are common in financial systems. In 2018, attackers replayed legitimate "
            "ATM withdrawal requests to extract money multiple times from a single authorized transaction. "
            "Quantum one-time tokens solve this by making each session physically non-reusable."
        ),
        "countermeasures": [
            "One-time consumption flag — each session can only be verified once",
            "Session tokens are marked as 'consumed' immediately after successful verification",
            "Timestamp validation prevents stale sessions from being accepted",
            "Database-level enforcement ensures atomic consume-on-verify semantics",
        ],
        "quantum_defense": (
            "Quantum mechanics provides the ultimate replay protection through the No-Cloning Theorem: "
            "a quantum state cannot be copied. In this simulation, we enforce the same principle digitally — "
            "each quantum session token is consumed upon first verification, and the 'consumed' flag "
            "is checked before any other validation. Attempting to reuse a session triggers immediate "
            "rejection with a 97% threat score."
        ),
    },
    "unauthorized": {
        "name": "Unauthorized Verification",
        "icon": "🚷",
        "severity": "HIGH",
        "severity_score": 90,
        "description": (
            "An unauthorized verification attack occurs when someone without proper "
            "credentials or role assignment attempts to verify a quantum signature. "
            "This represents a breach of the role-based access control (RBAC) system "
            "protecting the verification process."
        ),
        "how_it_works": [
            "An outside actor (not in the authorized verifier list) discovers a valid session ID.",
            "They attempt to verify the signature by submitting the session ID to the verification endpoint.",
            "The system checks the verifier's identity against the pre-configured authorized verifier list.",
            "The verifier's name is not found in the authorized set (e.g., only Bob and Charlie are allowed).",
            "The verification is rejected, and the unauthorized attempt is logged as a security event.",
        ],
        "real_world_example": (
            "In the 2013 Target breach, attackers used stolen HVAC vendor credentials to access "
            "Target's payment network — an unauthorized entity accessing a restricted system. "
            "Proper RBAC with quantum-backed identity verification would have blocked the lateral movement."
        ),
        "countermeasures": [
            "Pre-configured authorized verifier whitelist (configurable via environment variable)",
            "Every verification attempt logs the actor's identity for audit",
            "Immediate rejection with high threat score (90%) for unauthorized actors",
            "Environment-variable-based configuration allows dynamic access management",
        ],
        "quantum_defense": (
            "In a full quantum key distribution (QKD) system, only parties sharing an entangled "
            "key pair can participate in verification. This simulation enforces the principle through "
            "an authorized verifier list. The check happens at Step 2 of verification — before any "
            "sensitive signature data is revealed to the requester, preventing information leakage "
            "to unauthorized parties."
        ),
    },
    "channel": {
        "name": "Quantum Channel Manipulation",
        "icon": "📡",
        "severity": "HIGH",
        "severity_score": 88,
        "description": (
            "A channel manipulation attack targets the quantum communication channel itself. "
            "An eavesdropper (Eve) intercepts quantum bits in transit, disturbing their "
            "quantum states and degrading measurement consistency below the security threshold."
        ),
        "how_it_works": [
            "Eve positions herself on the quantum channel between Alice and Bob (man-in-the-middle).",
            "Eve intercepts qubits being transmitted and measures them to extract information.",
            "Quantum mechanics dictates that measurement disturbs the qubit's state (Heisenberg Uncertainty).",
            "The disturbed qubits arrive at Bob with degraded measurement consistency (below 80% threshold).",
            "The system detects the degradation and rejects the verification — eavesdropping is exposed.",
        ],
        "real_world_example": (
            "In 2017, researchers demonstrated that fiber-optic quantum channels could detect "
            "eavesdropping with >99.9% accuracy using BB84 protocol. Any interception attempt "
            "introduces measurable noise, which is exactly what this measurement threshold detects."
        ),
        "countermeasures": [
            "Measurement consistency threshold (80%) — below this indicates channel tampering",
            "Bell state measurement provides a quantum fingerprint that degrades under interception",
            "Pauli correction verification ensures quantum state integrity after teleportation",
            "Statistical analysis of measurement patterns can reveal sophisticated attack patterns",
        ],
        "quantum_defense": (
            "This is the most inherently quantum defense in the system. The measurement match percentage "
            "simulates the fidelity of quantum teleportation. In real quantum communication, any "
            "eavesdropping attempt (intercepting and re-sending qubits) introduces detectable noise "
            "due to the Heisenberg Uncertainty Principle. The 80% threshold in this system represents "
            "the minimum fidelity required to trust the quantum channel hasn't been compromised."
        ),
    },
}


# Attack simulation definitions (kept separate for runtime use)
ATTACK_TYPES = {
    "forgery": {
        "category": "FORGERY",
        "score": 94,
        "detail": "Message/signature binding has been altered. Hash mismatch detected in quantum-signed payload.",
    },
    "impersonation": {
        "category": "IMPERSONATION",
        "score": 92,
        "detail_fn": lambda row, attacker: (
            f"Identity mismatch: expected signer '{row['signer']}' but actor '{attacker}' attempted verification. "
            f"Quantum identity binding violated."
        ),
    },
    "replay": {
        "category": "REPLAY",
        "score": 97,
        "detail": "Session reuse detected. One-time quantum signature protocol violated — replay protection triggered.",
    },
    "unauthorized": {
        "category": "UNAUTHORIZED_VERIFICATION",
        "score": 90,
        "detail_fn": lambda row, attacker: (
            f"Unauthorized actor '{attacker}' attempted verification without proper role credentials."
        ),
    },
    "channel": {
        "category": "CHANNEL_MANIPULATION",
        "score": 88,
        "detail": "Quantum channel manipulation simulated. Measurement consistency degraded below safe threshold, indicating potential eavesdropping.",
    },
}


def get_attack_knowledge():
    """Return the full attack knowledge base for educational display."""
    return ATTACK_KNOWLEDGE_BASE


def simulate_attack(session_id, attack_type, attacker):
    """
    Simulate a cyber attack against a quantum-signed session.

    Supported attack types: forgery, impersonation, replay, unauthorized, channel.
    Each attack type has a predefined threat score and generates a detailed log entry.
    Returns detection result alongside educational content from the knowledge base.
    """
    row = one("SELECT * FROM signatures WHERE session_id=?", (session_id,))
    if not row:
        return {"ok": False, "error": "Session not found. Generate a signature first."}

    attack_type = attack_type.lower().strip()
    attack_def = ATTACK_TYPES.get(attack_type)

    if not attack_def:
        valid_types = ", ".join(sorted(ATTACK_TYPES.keys()))
        return {
            "ok": False,
            "error": f"Unknown attack type '{attack_type}'. Valid types: {valid_types}",
        }

    category = attack_def["category"]
    score = attack_def["score"]

    # Build detail string — some attacks use dynamic details based on session/attacker
    if "detail_fn" in attack_def:
        details = attack_def["detail_fn"](row, attacker)
    else:
        details = attack_def["detail"]

    log_event(session_id, category, attacker, score, details)

    # Include educational content from the knowledge base
    knowledge = ATTACK_KNOWLEDGE_BASE.get(attack_type, {})

    return {
        "ok": True,
        "session_id": session_id,
        "attacker": attacker,
        "category": category,
        "decision": "REJECT",
        "threat_score": score,
        "reason": details,
        "attack_info": {
            "name": knowledge.get("name", category),
            "icon": knowledge.get("icon", "⚠️"),
            "severity": knowledge.get("severity", "UNKNOWN"),
            "description": knowledge.get("description", ""),
            "how_it_works": knowledge.get("how_it_works", []),
            "real_world_example": knowledge.get("real_world_example", ""),
            "countermeasures": knowledge.get("countermeasures", []),
            "quantum_defense": knowledge.get("quantum_defense", ""),
        },
    }
