import os
import hashlib
from datetime import datetime, timezone
from database.db import one, execute

# Configurable via environment variable, comma-separated
_default_verifiers = "Bob,Charlie"
AUTHORIZED_VERIFIERS = set(
    v.strip()
    for v in os.environ.get("QDS_AUTHORIZED_VERIFIERS", _default_verifiers).split(",")
    if v.strip()
)

# Minimum measurement match threshold (%)
MEASUREMENT_THRESHOLD = 80


def _build_check(name, label, status, description, icon_pass="✅", icon_fail="🚫"):
    """Build a single verification check result entry."""
    return {
        "name": name,
        "label": label,
        "status": status,  # "pass", "fail", "skipped"
        "description": description,
        "icon": icon_pass if status == "pass" else icon_fail,
    }


def verify_signature(session_id, verifier):
    """
    Verify a quantum-inspired digital signature with step-by-step checks.

    Checks performed (in order):
    1. Session exists (anti-forgery)
    2. Verifier is authorized (role-based access)
    3. Session hasn't been consumed (anti-replay)
    4. Measurement quality above threshold (channel integrity)
    5. Hash integrity (re-compute SHA-256 and compare)

    Returns a result dict including a `checks` array with per-step details
    so the frontend can animate each verification stage.
    """
    checks = []
    now = datetime.now(timezone.utc).isoformat()

    # ── Check 1: Session Existence (Anti-Forgery) ───────────────────
    row = one("SELECT * FROM signatures WHERE session_id=?", (session_id,))

    if not row:
        checks.append(_build_check(
            "session_exists", "Session Lookup",
            "fail",
            f"No signature found for session '{session_id}'. This could indicate a forged or fabricated session ID.",
        ))
        return {
            "ok": False,
            "decision": "REJECT",
            "category": "FORGERY",
            "threat_score": 95,
            "reason": "Unknown session/signature — possible forgery attempt.",
            "checks": checks,
        }

    checks.append(_build_check(
        "session_exists", "Session Lookup",
        "pass",
        f"Session '{session_id}' found. Signature was generated by '{row['signer']}' on {row['created_at']}.",
    ))

    # ── Check 2: Authorization ──────────────────────────────────────
    if verifier not in AUTHORIZED_VERIFIERS:
        checks.append(_build_check(
            "authorization", "Authorization Check",
            "fail",
            f"Verifier '{verifier}' is not in the authorized verifier list ({', '.join(sorted(AUTHORIZED_VERIFIERS))}).",
        ))
        execute(
            "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
            (session_id, "UNAUTHORIZED_VERIFICATION", verifier, "REJECT", 90,
             f"Verifier '{verifier}' is not in the authorized list ({', '.join(sorted(AUTHORIZED_VERIFIERS))}).", now),
        )
        return {
            "ok": True,
            "decision": "REJECT",
            "category": "UNAUTHORIZED_VERIFICATION",
            "threat_score": 90,
            "reason": f"Verifier '{verifier}' is not authorized. Only {', '.join(sorted(AUTHORIZED_VERIFIERS))} may verify.",
            "checks": checks,
        }

    checks.append(_build_check(
        "authorization", "Authorization Check",
        "pass",
        f"Verifier '{verifier}' is authorized. Role-based access control passed.",
    ))

    # ── Check 3: Replay Detection ───────────────────────────────────
    if row["consumed"]:
        checks.append(_build_check(
            "replay", "Replay Detection",
            "fail",
            "This signature session has already been consumed. Re-use of a one-time quantum token is prohibited.",
        ))
        execute(
            "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
            (session_id, "REPLAY", verifier, "REJECT", 96,
             "Signature/session already consumed — replay attack detected.", now),
        )
        return {
            "ok": True,
            "decision": "REJECT",
            "category": "REPLAY",
            "threat_score": 96,
            "reason": "Replay attack: this session has already been used.",
            "checks": checks,
        }

    checks.append(_build_check(
        "replay", "Replay Detection",
        "pass",
        "Session has not been used before. One-time token is fresh and valid.",
    ))

    # ── Check 4: Channel Integrity (Measurement Match) ──────────────
    match_pct = row["measurement_match"]
    if match_pct < MEASUREMENT_THRESHOLD:
        checks.append(_build_check(
            "channel_integrity", "Channel Integrity",
            "fail",
            f"Measurement match is {match_pct}%, below the {MEASUREMENT_THRESHOLD}% threshold. "
            f"This indicates potential eavesdropping or quantum channel manipulation.",
        ))
        execute(
            "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
            (session_id, "CHANNEL_MANIPULATION", verifier, "REJECT", 85,
             f"Measurement match {match_pct}% is below the {MEASUREMENT_THRESHOLD}% threshold.", now),
        )
        return {
            "ok": True,
            "decision": "REJECT",
            "category": "CHANNEL_MANIPULATION",
            "threat_score": 85,
            "reason": f"Measurement consistency ({match_pct}%) is below the required {MEASUREMENT_THRESHOLD}% threshold.",
            "checks": checks,
        }

    checks.append(_build_check(
        "channel_integrity", "Channel Integrity",
        "pass",
        f"Measurement consistency is {match_pct}%, well above the {MEASUREMENT_THRESHOLD}% threshold. Quantum channel is secure.",
    ))

    # ── Check 5: Hash Integrity ─────────────────────────────────────
    recomputed_hash = hashlib.sha256(row["message"].encode()).hexdigest()
    stored_hash = row["message_hash"]

    if recomputed_hash != stored_hash:
        checks.append(_build_check(
            "hash_integrity", "Hash Integrity",
            "fail",
            f"SHA-256 hash mismatch! Stored: {stored_hash[:16]}... Computed: {recomputed_hash[:16]}... "
            f"The signed message may have been tampered with.",
        ))
        execute(
            "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
            (session_id, "FORGERY", verifier, "REJECT", 98,
             f"Hash integrity check failed. Stored hash does not match recomputed hash.", now),
        )
        return {
            "ok": True,
            "decision": "REJECT",
            "category": "FORGERY",
            "threat_score": 98,
            "reason": "Hash integrity failed — the message content appears to have been tampered with.",
            "checks": checks,
        }

    checks.append(_build_check(
        "hash_integrity", "Hash Integrity",
        "pass",
        f"SHA-256 hash verified. Stored and recomputed hashes match perfectly ({stored_hash[:16]}...).",
    ))

    # ── All Checks Passed — Accept and Consume ──────────────────────
    execute(
        "UPDATE signatures SET consumed=1,status='VERIFIED' WHERE session_id=?",
        (session_id,),
    )
    execute(
        "INSERT INTO events(session_id,category,actor,decision,threat_score,details,created_at) VALUES(?,?,?,?,?,?,?)",
        (session_id, "LEGITIMATE", verifier, "ACCEPT", 2,
         f"All protocol checks passed. Verified by {verifier}.", now),
    )
    return {
        "ok": True,
        "decision": "ACCEPT",
        "category": "LEGITIMATE",
        "threat_score": 2,
        "measurement_match": match_pct,
        "reason": "Signature verified successfully. All quantum protocol checks passed.",
        "checks": checks,
    }
